import "./dashboard.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div>
      <Navbar></Navbar>
      <h2>THIS IS DASHBOARD</h2>
      {children}
    </div>
  );
}