import "./auth.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div>
      <h2>THIS IS AUTH</h2>
      {children}
    </div>
  );
}