name: CI for SWEN746-PROJ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: swen610
          POSTGRES_USER: swen610
          POSTGRES_PASSWORD: qwerty123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U swen610 -d swen610"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Copy credentials
      run: |
        cp backend/config/github-credentials.yml backend/config/db.yml

    - name: Display Python version
      run: |
        python3 --version

    - name: Start server
      run: |
        python3 backend/src/server.py &
      env:
        POSTGRES_DB: swen610
        POSTGRES_USER: swen610
        POSTGRES_PASSWORD: qwerty123

    - name: Wait for server to start
      run: sleep 3

    - name: Run unit tests
      run: |
        python3 -m unittest discover -s backend/tests -p "*.py" -v