name: CI for SWEN746-PROJ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: swen610
          POSTGRES_USER: swen610
          POSTGRES_PASSWORD: qwerty123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U swen610 -d swen610"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install coverage codecov

    - name: Copy credentials
      run: |
        cp backend/config/github-credentials.yml backend/config/db.yml

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=backend/src:backend/tests:$PYTHONPATH
        python3 --version

    - name: Start server
      run: |
        cd backend
        python3 src/server.py &

    - name: Wait for PostgreSQL to start
      run: sleep 5

    - name: Run unit tests with coverage
      run: |
        cd backend
        coverage run -m unittest discover
        coverage xml
        
    - name: Generate Coverage Report
      run: |
        pytest --cov --cov-report=xml
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./backend/coverage.xml
